/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Estado del servicio. Estático, no toca la DB.
         */
        get: operations["apps_core_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Zonas
         * @description Lista las zonas activas ordenadas por nombre.
         */
        get: operations["apps_geo_api_listar_zonas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolver Zona
         * @description Resuelve la zona activa más cercana al centroide. 404 si sin cobertura.
         */
        post: operations["apps_geo_api_resolver_zona"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar
         * @description Busca canónicos por `q` con su precio más fresco por retailer en la zona.
         *
         *     404 si `zone_id` no existe o está inactiva (el service devuelve None).
         */
        get: operations["apps_catalog_api_buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle Producto
         * @description Detalle de un canónico en la zona: producto, precios actuales e historial.
         *
         *     404 si el producto no existe/inactivo o si `zone_id` no existe/inactiva
         *     (el service devuelve None).
         */
        get: operations["apps_catalog_api_detalle_producto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * HealthOut
         * @description Respuesta del endpoint de salud.
         */
        HealthOut: {
            /** Status */
            status: string;
        };
        /**
         * ZoneOut
         * @description Representación pública de una zona (subconjunto del modelo Zone).
         */
        ZoneOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** State */
            state: string;
        };
        /**
         * ResolveIn
         * @description Coordenadas del usuario para resolver su zona más cercana.
         */
        ResolveIn: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * CanonicalProductRefOut
         * @description Subconjunto público del producto canónico para el resultado de búsqueda.
         */
        CanonicalProductRefOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Unit */
            unit: string;
        };
        /**
         * PriceByRetailerOut
         * @description Precio más fresco de un retailer para un canónico en una zona.
         *
         *     `price`/`captured_at` son None cuando el retailer no tiene observación en la
         *     zona (entonces `is_available=False`). `price` se serializa como string del
         *     Decimal para no perder exactitud monetaria (PRD §8).
         */
        PriceByRetailerOut: {
            retailer: components["schemas"]["RetailerRefOut"];
            /** Retailer Product Id */
            retailer_product_id: string;
            /** Price */
            price?: string | null;
            /**
             * Currency
             * @default MXN
             */
            currency: string;
            /**
             * Is Available
             * @default false
             */
            is_available: boolean;
            /** Captured At */
            captured_at?: string | null;
            /** Url */
            url: string;
        };
        /**
         * RetailerRefOut
         * @description Referencia mínima a un retailer dentro de un precio.
         */
        RetailerRefOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /**
         * SearchResultOut
         * @description Un producto canónico matcheado con sus precios por retailer en la zona.
         */
        SearchResultOut: {
            canonical_product: components["schemas"]["CanonicalProductRefOut"];
            /** Prices */
            prices: components["schemas"]["PriceByRetailerOut"][];
        };
        /**
         * CanonicalProductDetailOut
         * @description Producto canónico expandido para el detalle (incluye `specs` libres).
         */
        CanonicalProductDetailOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Unit */
            unit: string;
            /** Specs */
            specs: {
                [key: string]: unknown;
            };
        };
        /**
         * PriceHistoryPointOut
         * @description Una lectura histórica de precio (una `PriceObservation`) con su retailer.
         *
         *     `price` se serializa como string del Decimal por exactitud monetaria
         *     (PRD §8). El historial combina todos los retailers en la zona, ordenado por
         *     `-captured_at` (la UI de F021 puede agrupar por retailer).
         */
        PriceHistoryPointOut: {
            retailer: components["schemas"]["RetailerRefOut"];
            /** Price */
            price: string;
            /**
             * Currency
             * @default MXN
             */
            currency: string;
            /** Is Available */
            is_available: boolean;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
        };
        /**
         * ProductDetailOut
         * @description Detalle de un canónico: producto, precios actuales por retailer e historial.
         *
         *     `prices` reutiliza el ensamblado "precio más fresco por retailer/zona" de
         *     F015; `history` son las últimas N observaciones en la zona (orden
         *     `-captured_at`).
         */
        ProductDetailOut: {
            canonical_product: components["schemas"]["CanonicalProductDetailOut"];
            /** Prices */
            prices: components["schemas"]["PriceByRetailerOut"][];
            /** History */
            history: components["schemas"]["PriceHistoryPointOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apps_core_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    apps_geo_api_listar_zonas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneOut"][];
                };
            };
        };
    };
    apps_geo_api_resolver_zona: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneOut"];
                };
            };
        };
    };
    apps_catalog_api_buscar: {
        parameters: {
            query: {
                q: string;
                zone_id: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"][];
                };
            };
        };
    };
    apps_catalog_api_detalle_producto: {
        parameters: {
            query: {
                zone_id: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailOut"];
                };
            };
        };
    };
}
