/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Estado del servicio. Estático, no toca la DB.
         */
        get: operations["apps_core_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Zonas
         * @description Lista las zonas activas ordenadas por nombre.
         */
        get: operations["apps_geo_api_listar_zonas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retailers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Retailers
         * @description Lista todos los retailers (incluye inactivos) ordenados por nombre.
         */
        get: operations["apps_geo_api_listar_retailers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolver Zona
         * @description Resuelve la zona activa más cercana al centroide. 404 si sin cobertura.
         */
        post: operations["apps_geo_api_resolver_zona"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar
         * @description Busca canónicos por `q` con su precio más fresco por retailer en la zona.
         *
         *     404 si `zone_id` no existe o está inactiva (el service devuelve None).
         */
        get: operations["apps_catalog_api_buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle Producto
         * @description Detalle de un canónico en la zona: producto, precios actuales e historial.
         *
         *     404 si el producto no existe/inactivo o si `zone_id` no existe/inactiva
         *     (el service devuelve None).
         */
        get: operations["apps_catalog_api_detalle_producto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Listas
         * @description Lista las listas de la sesión (`X-Session-Key`). 400 sin header.
         */
        get: operations["apps_lists_api_listar_listas"];
        put?: never;
        /**
         * Crear Lista
         * @description Crea una lista para la sesión. 400 sin header; 422 cuerpo inválido.
         */
        post: operations["apps_lists_api_crear_lista"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{list_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle Lista
         * @description Detalle de una lista de la sesión (ítems + subtotal/total). 400 sin header; 404 ajena.
         */
        get: operations["apps_lists_api_detalle_lista"];
        put?: never;
        post?: never;
        /**
         * Eliminar Lista
         * @description Borra una lista de la sesión (sin body). 400 sin header; 404 si no es suya; 204 si ok.
         */
        delete: operations["apps_lists_api_eliminar_lista"];
        options?: never;
        head?: never;
        /**
         * Actualizar Lista
         * @description Actualiza nombre y/o zona de una lista de la sesión. 400 sin header; 404 si no es suya.
         */
        patch: operations["apps_lists_api_actualizar_lista"];
        trace?: never;
    };
    "/api/lists/{list_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agregar Item
         * @description Agrega un SKU con snapshot inmutable. 400 sin header; 404 lista/SKU; 422 sin precio.
         */
        post: operations["apps_lists_api_agregar_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{list_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar Item
         * @description Quita un ítem de la lista de la sesión (sin body). 400 sin header; 404; 204 si ok.
         */
        delete: operations["apps_lists_api_eliminar_item"];
        options?: never;
        head?: never;
        /**
         * Actualizar Item
         * @description Cambia la cantidad de un ítem (el snapshot no se toca). 400 sin header; 404; 422 cantidad.
         */
        patch: operations["apps_lists_api_actualizar_item"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * HealthOut
         * @description Respuesta del endpoint de salud.
         */
        HealthOut: {
            /** Status */
            status: string;
        };
        /**
         * ZoneOut
         * @description Representación pública de una zona (subconjunto del modelo Zone).
         */
        ZoneOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** State */
            state: string;
        };
        /**
         * RetailerOut
         * @description Representación de soporte/diagnóstico de un retailer (F018).
         *
         *     Expone el modelo de pricing y el estado del scraper para que la UI/operador
         *     vea de un vistazo qué fuentes están activas/pausadas/no viables.
         */
        RetailerOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Pricing Model */
            pricing_model: string;
            /** Scraper Status */
            scraper_status: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * ResolveIn
         * @description Coordenadas del usuario para resolver su zona más cercana.
         */
        ResolveIn: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * CanonicalProductRefOut
         * @description Subconjunto público del producto canónico para el resultado de búsqueda.
         *
         *     F031: `mass_kg` (peso de una pieza canónica) es el factor de conversión que
         *     permite a la UI explicar la normalización; None si el canónico no es
         *     normalizable. String Decimal por exactitud.
         */
        CanonicalProductRefOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Unit */
            unit: string;
            /** Mass Kg */
            mass_kg?: string | null;
        };
        /**
         * PriceByRetailerOut
         * @description Precio más fresco de un retailer para un canónico en una zona.
         *
         *     `price`/`captured_at` son None cuando el retailer no tiene observación en la
         *     zona (entonces `is_available=False`). `price` se serializa como string del
         *     Decimal para no perder exactitud monetaria (PRD §8).
         *
         *     F031: `price` es el valor NATIVO del retailer (transparencia: "listado a
         *     $X/ton"); `sale_unit` es su unidad estructurada (`""` = desconocida). La
         *     comparación cross-retailer usa los campos NORMALIZADOS `price_per_piece`
         *     (titular de obra) y `price_per_kg` (base de orden/menor-precio). Cualquiera
         *     de los dos es None cuando no se puede normalizar (falta `mass_kg`, unidad
         *     desconocida o sin precio en la zona). También como string Decimal.
         */
        PriceByRetailerOut: {
            retailer: components["schemas"]["RetailerRefOut"];
            /** Retailer Product Id */
            retailer_product_id: string;
            /** Price */
            price?: string | null;
            /**
             * Currency
             * @default MXN
             */
            currency: string;
            /**
             * Is Available
             * @default false
             */
            is_available: boolean;
            /** Captured At */
            captured_at?: string | null;
            /** Url */
            url: string;
            /**
             * Sale Unit
             * @default
             */
            sale_unit: string;
            /** Price Per Piece */
            price_per_piece?: string | null;
            /** Price Per Kg */
            price_per_kg?: string | null;
        };
        /**
         * RetailerRefOut
         * @description Referencia mínima a un retailer dentro de un precio.
         */
        RetailerRefOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /**
         * SearchResultOut
         * @description Un producto canónico matcheado con sus precios por retailer en la zona.
         */
        SearchResultOut: {
            canonical_product: components["schemas"]["CanonicalProductRefOut"];
            /** Prices */
            prices: components["schemas"]["PriceByRetailerOut"][];
        };
        /**
         * CanonicalProductDetailOut
         * @description Producto canónico expandido para el detalle (incluye `specs` libres).
         *
         *     F031: incluye `mass_kg` (factor de conversión para la normalización; None si
         *     no es normalizable). String Decimal por exactitud.
         */
        CanonicalProductDetailOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Unit */
            unit: string;
            /** Mass Kg */
            mass_kg?: string | null;
            /** Specs */
            specs: {
                [key: string]: unknown;
            };
        };
        /**
         * PriceHistoryPointOut
         * @description Una lectura histórica de precio (una `PriceObservation`) con su retailer.
         *
         *     `price` se serializa como string del Decimal por exactitud monetaria
         *     (PRD §8). El historial combina todos los retailers en la zona, ordenado por
         *     `-captured_at` (la UI de F021 puede agrupar por retailer).
         *
         *     F031: cada punto gana `sale_unit` para ETIQUETAR su unidad nativa (`""` =
         *     desconocida). El historial NO se normaliza (fuera de alcance): `price` sigue
         *     siendo el valor nativo.
         */
        PriceHistoryPointOut: {
            retailer: components["schemas"]["RetailerRefOut"];
            /** Price */
            price: string;
            /**
             * Currency
             * @default MXN
             */
            currency: string;
            /** Is Available */
            is_available: boolean;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /**
             * Sale Unit
             * @default
             */
            sale_unit: string;
        };
        /**
         * ProductDetailOut
         * @description Detalle de un canónico: producto, precios actuales por retailer e historial.
         *
         *     `prices` reutiliza el ensamblado "precio más fresco por retailer/zona" de
         *     F015; `history` son las últimas N observaciones en la zona (orden
         *     `-captured_at`).
         */
        ProductDetailOut: {
            canonical_product: components["schemas"]["CanonicalProductDetailOut"];
            /** Prices */
            prices: components["schemas"]["PriceByRetailerOut"][];
            /** History */
            history: components["schemas"]["PriceHistoryPointOut"][];
        };
        /**
         * UserListOut
         * @description Lista de cotización (resumen): metadatos + conteo de ítems.
         *
         *     `zone_id` es None cuando la lista aún no tiene zona asignada. `item_count`
         *     es la cantidad de ítems (filas), no la suma de cantidades.
         */
        UserListOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Zone Id */
            zone_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Item Count */
            item_count: number;
        };
        /**
         * UserListCreateIn
         * @description Cuerpo de POST /lists: nombre obligatorio y zona opcional.
         */
        UserListCreateIn: {
            /** Name */
            name: string;
            /** Zone Id */
            zone_id?: string | null;
        };
        /**
         * UserListDetailOut
         * @description Detalle de una lista: el resumen + sus ítems y los totales calculados.
         *
         *     `subtotal`/`total` reutilizan `services.subtotal_lista` (F009); en el MVP no
         *     hay impuestos ni envío, así que `total == subtotal`. Decimales como string.
         */
        UserListDetailOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Zone Id */
            zone_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Item Count */
            item_count: number;
            /** Items */
            items: components["schemas"]["UserListItemOut"][];
            /** Subtotal */
            subtotal: string;
            /** Total */
            total: string;
        };
        /**
         * UserListItemOut
         * @description Ítem de una lista: SKU, cantidad y snapshot inmutable del precio.
         *
         *     `captured_price`/`captured_at` son el snapshot que se fijó al agregar el ítem
         *     y NUNCA cambian después (CA2 de C1). `line_total = quantity * captured_price`.
         *     Los `Decimal` se serializan como string por exactitud monetaria (PRD §8).
         */
        UserListItemOut: {
            /** Id */
            id: string;
            /** Retailer Product Id */
            retailer_product_id: string;
            retailer: components["schemas"]["RetailerRefOut"];
            /** Product Name */
            product_name: string;
            /** Quantity */
            quantity: number;
            /** Captured Price */
            captured_price: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Line Total */
            line_total: string;
        };
        /**
         * UserListPatchIn
         * @description Cuerpo de PATCH /lists/{id}: campos opcionales (parcial).
         *
         *     `zone_id` admite tres estados: ausente (no tocar), una zona, o None explícito
         *     (desasignar la zona).
         */
        UserListPatchIn: {
            /** Name */
            name?: string | null;
            /** Zone Id */
            zone_id?: string | null;
        };
        /**
         * UserListItemCreateIn
         * @description Cuerpo de POST /lists/{id}/items: SKU + cantidad (>= 1).
         */
        UserListItemCreateIn: {
            /** Retailer Product Id */
            retailer_product_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /**
         * UserListItemPatchIn
         * @description Cuerpo de PATCH /lists/{id}/items/{item_id}: nueva cantidad (>= 1).
         */
        UserListItemPatchIn: {
            /** Quantity */
            quantity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apps_core_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    apps_geo_api_listar_zonas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneOut"][];
                };
            };
        };
    };
    apps_geo_api_listar_retailers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetailerOut"][];
                };
            };
        };
    };
    apps_geo_api_resolver_zona: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneOut"];
                };
            };
        };
    };
    apps_catalog_api_buscar: {
        parameters: {
            query: {
                q: string;
                zone_id: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"][];
                };
            };
        };
    };
    apps_catalog_api_detalle_producto: {
        parameters: {
            query: {
                zone_id: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailOut"];
                };
            };
        };
    };
    apps_lists_api_listar_listas: {
        parameters: {
            query?: never;
            header?: {
                x_session_key?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"][];
                };
            };
        };
    };
    apps_lists_api_crear_lista: {
        parameters: {
            query?: never;
            header?: {
                x_session_key?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserListCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"];
                };
            };
        };
    };
    apps_lists_api_detalle_lista: {
        parameters: {
            query?: never;
            header?: {
                x_session_key?: string | null;
            };
            path: {
                list_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListDetailOut"];
                };
            };
        };
    };
    apps_lists_api_eliminar_lista: {
        parameters: {
            query?: never;
            header?: {
                x_session_key?: string | null;
            };
            path: {
                list_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_lists_api_actualizar_lista: {
        parameters: {
            query?: never;
            header?: {
                x_session_key?: string | null;
            };
            path: {
                list_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserListPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"];
                };
            };
        };
    };
    apps_lists_api_agregar_item: {
        parameters: {
            query?: never;
            header?: {
                x_session_key?: string | null;
            };
            path: {
                list_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserListItemCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItemOut"];
                };
            };
        };
    };
    apps_lists_api_eliminar_item: {
        parameters: {
            query?: never;
            header?: {
                x_session_key?: string | null;
            };
            path: {
                list_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apps_lists_api_actualizar_item: {
        parameters: {
            query?: never;
            header?: {
                x_session_key?: string | null;
            };
            path: {
                list_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserListItemPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItemOut"];
                };
            };
        };
    };
}
