# Generated by Django 6.0.6 on 2026-06-13 22:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_key', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(blank=True, default='Mi cotización', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=16)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_lists', to='geo.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('captured_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('captured_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('retailer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='catalog.retailerproduct')),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.userlist')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
