# Generated by Django 6.0.6 on 2026-06-13 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('pieza', 'Pieza'), ('saco', 'Saco'), ('m', 'Metro'), ('kg', 'Kilogramo')], max_length=16)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetailerProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('external_sku', models.CharField(max_length=200)),
                ('raw_name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True)),
                ('unit_raw', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('match_status', models.CharField(choices=[('unmatched', 'Sin asignar'), ('auto', 'Automático'), ('manual', 'Manual'), ('rejected', 'Rechazado')], default='unmatched', max_length=16)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('canonical_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_products', to='catalog.canonicalproduct')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='geo.retailer')),
            ],
            options={
                'ordering': ['retailer', 'raw_name'],
                'unique_together': {('retailer', 'external_sku')},
            },
        ),
    ]
