# Generated by Django 6.0.6 on 2026-06-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalproduct',
            name='mass_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso de UNA pieza/unidad canónica en kg (NMX masa nominal × longitud). Null = no normalizable: la UI cae a solo-precio-nativo.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='retailerproduct',
            name='sale_unit',
            field=models.CharField(blank=True, choices=[('pieza', 'Pieza'), ('kg', 'Kilogramo'), ('tonelada', 'Tonelada'), ('saco', 'Saco'), ('m', 'Metro')], help_text='Unidad en que el retailer LISTA el precio. Blank = desconocida (no normalizable). Se cura en Admin / la fija el adapter.', max_length=16),
        ),
    ]
