# Generated by Django 6.0.6 on 2026-06-13 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('base_url', models.URLField()),
                ('pricing_model', models.CharField(choices=[('zone_cookie', 'Zona por cookie'), ('distributor_subpath', 'Distribuidor por subpath')], max_length=32)),
                ('scraper_status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('non_viable', 'No viable')], default='active', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('state', models.CharField(max_length=120)),
                ('centroid_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetailerLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('external_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('subpath', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='geo.retailer')),
            ],
            options={
                'ordering': ['retailer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneLocationMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('retailer_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_maps', to='geo.retailerlocation')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_maps', to='geo.zone')),
            ],
            options={
                'ordering': ['zone', '-is_primary'],
                'unique_together': {('zone', 'retailer_location')},
            },
        ),
    ]
