# Generated by Django 6.0.6 on 2026-06-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerlocation',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
