# Generated by Django 6.0.6 on 2026-06-13 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'Correcta'), ('partial', 'Parcial'), ('failed', 'Fallida')], max_length=16)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_runs', to='geo.retailer')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_runs', to='geo.zone')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('xhr', 'XHR / API'), ('html', 'HTML'), ('playwright', 'Playwright')], max_length=16)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('retailer_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='geo.retailerlocation')),
                ('retailer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='catalog.retailerproduct')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='geo.zone')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['retailer_product', 'zone', '-captured_at'], name='price_obs_rp_zone_capt_idx')],
            },
        ),
    ]
