# Generated by Django 6.0.6 on 2026-07-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperun',
            name='search_term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='triggered_by',
            field=models.CharField(choices=[('command', 'Comando'), ('search', 'Búsqueda en vivo')], default='command', max_length=16),
        ),
    ]
