# Generated by Django 6.0.6 on 2026-07-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_scraperun_search_term_scraperun_triggered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceobservation',
            name='scrape_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='prices.scraperun'),
        ),
    ]
